#pragma once

#define WASM_PAGE_SIZE        (1024 * 64) /* 64KB */
#define WASM_MEMORY_PAGES_MAX (1 << 16)   /* 32,768 Pages ~4GB */
#define WASM_STACK_SIZE       (1 << 19)   /* 512KB */

/* Wasm initialization functions generated by the compiler */
#define AWSM_ABI_INITIALIZE_GLOBALS "populate_globals"
#define AWSM_ABI_INITIALIZE_MEMORY  "populate_memory"
#define AWSM_ABI_INITIALIZE_TABLE   "populate_table"
#define AWSM_ABI_INITIALIZE_LIBC    "wasmf___init_libc"
#define AWSM_ABI_ENTRYPOINT         "wasmf_main"

#define AWSM_ABI_STARTING_PAGES "starting_pages"
#define AWSM_ABI_MAX_PAGES      "max_pages"

/* functions in the module to lookup and call per sandbox. */
typedef int32_t (*awsm_abi_entrypoint_fn_t)(int32_t a, int32_t b);
typedef void (*awsm_abi_init_globals_fn_t)(void);
typedef void (*awsm_abi_init_mem_fn_t)(void);
typedef void (*awsm_abi_init_tbl_fn_t)(void);
typedef void (*awsm_abi_init_libc_fn_t)(int32_t, int32_t);
