client-cifar10:
	cat ./cifar10/airplane1.bmp | http :10019

client-ekf:
	cat ./ekf/ekf_raw.dat | http :10000

client-gocr:
	cat ./gocr/hyde.pnm | http :10006

client-lpd:
	cat ./lpd/Cars0.png | http :10012

client-resize:
	cat ./resize/shrinking_man_large.jpg | http :10018
